variables:
  # REGISTRY: registry.k8s.datafortress.cloud
  REGISTRY: localhost:5000
# before_script:
#   - docker login -u df -p  $REGISTRY

stages:
  - build
  - deploy

build-docker:
  stage: build
  image: docker:24.0.5
  tags:
    - contabo
  script:
    - docker pull $REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH || true
    - docker build --cache-from $REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH -t $REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH .
    - docker push $REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH

apply-kubectl:
  stage: deploy
  tags:
    - contabo
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  dependencies:
    - build-docker
  script:
    # for every .yaml file in kubernetes/, replace "latest" with $CI_COMMIT_BRANCH
    - sed -i "s/:latest/:$CI_COMMIT_BRANCH/g" kubernetes/*.yaml
    - kubectl apply -f kubernetes/
    - kubectl rollout restart -f kubernetes/ || true
  environment: production