version: "3"
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-tradingbot:/var/lib/postgresql/data

  tradingbot-baseimage:
    image: guestros/tradingbot22-backend:latest
    build: .
    container_name: tradingbot-backend
    ports:
      - "8000:8000"
    environment:
      - PSQL_URL=postgres:postgres@postgres:5432/postgres


volumes:
  postgres-tradingbot:
