version: "3"
services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - trading-postgres-data:/var/lib/postgresql/data

volumes:
  trading-postgres-data: