apiVersion: batch/v1
kind: CronJob
metadata:
  name: "postgres-backup"
  namespace: tradingbot22
spec:
  schedule: "1 2 * * 1" # help: https://crontab.guru/#30_15-21_*_*_*
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: guestros/postgres-s3-backup:latest
            imagePullPolicy: Always
            env:
            - name: PSQL_HOST
              value: "postgres-service"
            - name: PSQL_PORT
              value: "5432"
            - name: S3_BUCKET
              value: "backup-tradingbot22"
            - name: S3_REGION
              value: "eu-central-1"
            - name: S3_ENDPOINT
              value: "https://s3.eu-central-1.amazonaws.com"
            ## secrets
            # psql
            - name: PSQL_USER
              value: postgres
            - name: PSQL_PASSWORD
              value: postgres
            # AWS
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3backuptarget
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3backuptarget
                  key: AWS_SECRET_ACCESS_KEY
          restartPolicy: OnFailure