---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
  creationTimestamp: null
  name: basic-auth-trading
  namespace: tradingbot
spec:
  encryptedData:
    auth: AgAoZCAFajtCX70XhJtW7iTX9rLmdbiQBdjq9T+ld8QAo1faX6wtTlRYa3VxEUSjmHyhecy5P2VAuLHKuFQi8fQ7mTYIgrQzvi70mIhK0o9RTbOKUkdz/guk9Cp7y9Ub8wd0Ep0eHNqvoLArSm3MvOhydrtsx5rwtMdH09GAlKkQOi7HBoEmF/hZKvMyFKEagtHt3I4QwjziwlGAO41OW6P0zCk6fl7sGIfxpk5gbr1J0/1mooifJTqJpI85XpQ5cdFNv9ulieZ9DcxvJcu4sRfMAhfP6u3FsPWWcCI0ixUcMtl0s/KjojEwMVJjLmfdrC6fKIfm8bei0/2oRn/BvUFTVJemopXwUK2kH/sUFIqWMyqmLdwg4eFu0bMRBk3XJiJUITDnc0kxQHzU2b9rWbsoGuqhWfu9wq4C+xRvgYH5D9VKtbLXUcZITUdDbq8yNz8nLbaUyeScIO8gXM4ONctwLhFtIFs99br3SumCgYo3zFcn28VGyg+RekpwgNMsemp5j837O7EyoGv6wG16qL83I5BgPrDCHd4eJCT5HMlOTjerujpzFsRaKsMgowY3G9UVSLo+2MToHg8dNA4pQ641nCzb+w06c6li3EbY/MCp7iopgcWU16y4XKV/pwv5jiWyuJP5ZMMCLKdgaj4QU8NdWmUMwgj7rQD2luE1HZCsrWZXmWRSXXvAzwfRh3T73Ep2qURGBnGyNTT7/Ixl8itokltp79OJDpueaMaj/ZJqaq1VNdY18Pnkc8WRHGCu
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth-trading
      namespace: tradingbot
