apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: postgres-tradingbot
  name: postgres-tradingbot
  namespace: tradingbot22
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
status: {}
