---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: psql-secret
  namespace: tradingbot
spec:
  encryptedData:
    password: AgCG8GKGXAZ3js2vrK1qwAepL3Z7CKGK00nHXZQNk8P6nxJFk8Ry7I0xoejq8pNMrVBOt5PHrx5eU+Ll/TqwfLCAYA83lqhB3Z6MWKL96RaA/In/zI0gxthMivrUb9sHfSD96cld8PCp+C9OEI6Ypd0rCbpECSOjcZVIERURvsmjjbn3pd+/uzjl/hoOHtrPnGxjf7JAxUm5zE9dWlWdMzx4HIKQNizO9VjlilX1z0Y3i7BR1juBiPeesc0qosHkFNKPNQnQpjMy9iMT+RwQ6vrcH0KV84yawsvAJYKcCzUj5Q9lOiPTDaVzzCydqQyw2jy7Abgku7qAH/hg/+rw9T/yFUz39hlV6AjdpMoKdVy5Y1uvPz+xuoL5CxIH1hU7D0nt9qoT2r9X+luPQOvpZYJPT+8bcOwV3/gIrl4hk3XM1yJFrEJVQWJxDNQlvIifdUBpm1AN/UsYr6H6TFN54O7E7UwQhgUD5p9aEQxXfaXbZwWGUMn6s00Wa+k71LpQFsB3uDVNwaF56D28EypmB9pjSKUvew7QK1i9VnmDWKL+Xop5sS1iflzEv15ABVxleTCCBWGBJ+X+4jtbIxAolP8/P111URHoBF3FEeB7LdSWrCza7y8/RojhleP3OMo+xi1niM5EZOoyme/OM0sktQmtv5aTsEiLinC/r/5FDCCD0slo0fwacNINSbzQkmoHTN7qoDM12vW4Y0W+A89OL1BP54c2mqcVfBg=
    username: AgA9RWdZwyteTwmNbZhbqprNidirUF/gYQd4s0MqSfipg89zrxl0hVdP8EGR9nUGpxv8qliynV+l3VwUWIaegMUI8VBk8fn1RBKAoswBKBPc3CjPgmEDch4NTfFjvadgIm88bm8YpKrnUQrq1ptW6BlTcOJPGVObYDHar4qC9dJQUfXBnIqLuu2qdUy30V/u6Wr8LSXymiXFcJSU96mqk/tiCuIGq0xjdVNFWdtFnxxT7rc2HU8SNKIB1I/EfMl6NwRXgzHjY04ei8pZ0POA6N+gaduA3C0K9N//hOMcHj1yfz3KdU+eZowRKsuGEI3galJVnEz0i0Z0UwXxKDGsatCUHgUL8uA/M2i01zZ24Ojfjw21zl8byaM3HH2gwujz07IsZySjicv8wzjbMi83qZOcm9O5Rhy9Uc/mfFU08RDE1SK6j4rqGx+0QZQww7PQqypURMwFO8FDvyagx8TRtpKaCkKS34aRIpQ8tROB2W3sOHlhQntYaQopcFcHN/fn7U+Vqe6WNrYjQVg490Ugrr9QS6gv66Yw7oImxmqnYhuA54DjflmHFSBK8qSnflS75F+IxctyAb0gKmWZSD6DRAFyEhG685weTdkvcKCC8JWuPmIxchilASo/ZLJUgaMsxjxrvoa+J+1jxNRoDHjLvrpJSjDbzuvVZdfELE1wOenQ+zF8pgr/4dfi1+V6fBubfL0JmioTfkvqtw==
  template:
    metadata:
      creationTimestamp: null
      name: psql-secret
      namespace: tradingbot
