apiVersion: batch/v1
kind: CronJob
metadata:
  name: stoploss-takeprofit-checker
  namespace: tradingbot22
spec:
  schedule: "*/30 * * * *" # every 30 min
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: stoploss-takeprofit-checker
            image: buildpack-deps:curl
            args:
            - /bin/sh
            - -ec
            - curl http://tradingbot-baseimage-service:8000/stoplosscheck
          restartPolicy: Never