---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tradingbot-secret
  namespace: tradingbot
spec:
  encryptedData:
    alphavantage_key: AgAQ1BdEjMTJTnWyGmh7RrJ+4i9cu3GURyVDtb1ZdgXFKL3QjR5K9vFdWTm2J5TbIdRl1rqvhdKNMskrbuaclYKSTRx+VMK5nnsGjTih2DR8APT+cJQTnaAlnLZtcAeCJXq/VJB7+BmliT+JvTEs2tFJeLactLnrCKFYk8bQM/9OM8fa1cx1XGew1rsu8gub0GtfqAJ8f0eZRLbddpy33SQJ3a2j4Zh9hXEj7dKjoe6AhYAygHcKhVExEiXvj8t+4jfrrugGkKYTBaFY/lQAw4a7kED5TUSu+b25CxhLF9/gMj6YP5LC2nnLwthsmajhicc1ZmaeyXX3RfSYF7sNOM2vaP8I3tUNZPFnH6C7CM74/5i+H9ZViMeBy0jBd4uBT51PUS6taxjTWVrfNmbCHNJu5oZt57RUfeGf5eVBJZX3hmRynGjVxpJVvQDiGRkcRUicF1FVwSXhBFX7cvDKkXNL2nOC+KACS87EYl+zMMPGlMhRzugaabv9AiMQ0n8wdZjDGp7aQnIn1xQ6UoO0AXdOpLr/GgU4hSLl5qrg2qS8qh3Go4d3AxwtIShzo4dep95KEir1+7hjnkYUMwS+wOYgoAE+eKh+zxlK04znLgiu7iYrovOiW5stUELnTIHK8LTJgdBjQsNHPPvQFiw6mR3vOaZw8zTOO2ddZgEt+jbAYN3Lt7aZcgGeDdIufYsNYXAtC7XE3Fz11yT470NVhHyU
  template:
    metadata:
      creationTimestamp: null
      name: tradingbot-secret
      namespace: tradingbot # 
