apiVersion: batch/v1
kind: CronJob
metadata:
  name: tradingbot22-data-update
  namespace: tradingbot22
spec:
  schedule: "0 23 */1 * *"
  # schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tradingbot22-data-update
            image: buildpack-deps:curl
            args:
            - /bin/sh
            - -ec
            - curl http://tradingbot-baseimage-service:8000/update
          restartPolicy: Never